development:
  adapter: postgresql
  encoding: unicode
  database: sample_development
  username: dev
  password: niraj
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: sample_development
  username: postgres
  password:
  host: localhost
  port: 5432
